[theme]
primaryColor = "#ccf1f1"           # Soft teal - accent
backgroundColor = "#035dad"        # Deep blue - page background
secondaryBackgroundColor = "#1e4e8c"  # Muted deep sky blue - widget containers
# secondaryBackgroundColor = "#2c5fa3"  # Medium soft navy

textColor = "#f4fbfb"              # Very light cyan - readable text
font ='monospace'
